### ISSUE TITLE
Error in magic_calib_to_dl1.py with MCP-v0.3.1

### ISSUE THREAD

**Issue by abhradeep-1996** [cta-observatory/magic-cta-pipe#235]
While running magic_calib_to_dl1.py, it produced the following error message:
"
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
Traceback (most recent call last):
  File "magic_calib_to_dl1.py", line 47, in <module>
    from astropy import units as u
  File "/home/abhradeep.roy/miniconda3/envs/magic-lst1_v0.3.1/lib/python3.8/site-packages/astropy/__init__.py", line 42, in <module>
    from . import config as _config  # noqa: E402
  File "/home/abhradeep.roy/miniconda3/envs/magic-lst1_v0.3.1/lib/python3.8/site-packages/astropy/config/__init__.py", line 10, in <module>
    from .configuration import *
  File "/home/abhradeep.roy/miniconda3/envs/magic-lst1_v0.3.1/lib/python3.8/site-packages/astropy/config/configuration.py", line 24, in <module>
    from astropy.utils import find_current_module, silence
  File "/home/abhradeep.roy/miniconda3/envs/magic-lst1_v0.3.1/lib/python3.8/site-packages/astropy/utils/__init__.py", line 18, in <module>
    from .decorators import *  # noqa
  File "/home/abhradeep.roy/miniconda3/envs/magic-lst1_v0.3.1/lib/python3.8/site-packages/astropy/utils/decorators.py", line 15, in <module>
    from .exceptions import (AstropyDeprecationWarning, AstropyUserWarning,
  File "/home/abhradeep.roy/miniconda3/envs/magic-lst1_v0.3.1/lib/python3.8/site-packages/astropy/utils/exceptions.py", line 11, in <module>
    from erfa import ErfaError, ErfaWarning  # noqa
  File "/home/abhradeep.roy/miniconda3/envs/magic-lst1_v0.3.1/lib/python3.8/site-packages/erfa/__init__.py", line 5, in <module>
    from .version import version as __version__  # noqa
  File "/home/abhradeep.roy/miniconda3/envs/magic-lst1_v0.3.1/lib/python3.8/site-packages/erfa/version.py", line 25, in <module>
    from . import ufunc
ImportError: numpy.core.multiarray failed to import
"

Probably the reason is version incompatibility between various dependencies.

**Comment by abhradeep-1996** [comment]
I think I have solved the issue for now. There were a lot of version incompatibilities with numpy 1.21.6.
I am giving the steps below to solve the issues:
1. Error: RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
    Solution: downgrade pyerfa 2.0.0.3 to pyerfa 2.0.0.1
                     downgrade numba 0.58.0 to numba 0.57.0

Then several packages needed recompilation according to these downgraded packages. So, I had to follow these steps:
1. Error: ImportError: numpy.core.multiarray failed to import
    Solution: uninstall and reinstall matplotlib 3.7.3
2. Error: ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
    Solution: uninstall and reinstall eventio 1.11.5
3. Error: ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
    Solution: uninstall and reinstall h5py 3.11.0
4. Error: ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 232 from C header, got 216 from PyObject
    Solution: uninstall and reinstall tables-3.8.0

Now, "magic_calib_to_dl1.py" is working properly with MCP-0.3.1.

**Comment by aleberti** [comment]
I think I will close this issue. v0.3.1 is quite old (at the time of the opening of the issue, v0.4.1 was already available, and possibly the issue was already fixed there). I suggest to always try to use the latest version. More importantly, since now LTS old data are produced with lstchain 0.9.x and more recent ones with lstchain 0.10.x, only MCP>=v0.4.2 can deal with this situation. So, please update to the latest version of MCP if you can, but beware of the "NOTE ON OLD RELEASES" in https://github.com/cta-observatory/magic-cta-pipe/blob/master/README.rst, which most likely could affect you.
