### ISSUE TITLE
missing subarray information for LST-2,-3,-4

### ISSUE THREAD

**Issue by giorgio-pirola** [cta-observatory/magic-cta-pipe#237]
When running the coincidence search on real data, the scripts try to write in the output file the subarray information from the input files, and it fails in finding the information for LST-2,3,4: In magicctapipe/scripts/lst1_magic/lst1_magic_event_coincidence.py, at line 565 (v.0.4.1):

Giving this error:

Traceback (most recent call last):

  File "/fefs/home/giorgio.pirola/ctasoft/magic-cta-pipe/magicctapipe/scripts/lst1_magic/lst1_magic_event_coincidence.py", line 648, in <module>

    main()

  File "/fefs/home/giorgio.pirola/ctasoft/magic-cta-pipe/magicctapipe/scripts/lst1_magic/lst1_magic_event_coincidence.py", line 637, in main

    event_coincidence(

  File "/fefs/home/giorgio.pirola/ctasoft/magic-cta-pipe/magicctapipe/scripts/lst1_magic/lst1_magic_event_coincidence.py", line 566, in event_coincidence

    tel_descriptions[k] = subarray_lst.tel[k]

Maybe I am doing something wrong, but since now in the configuration file is necessary to specify all the 6 telescopes with their IDs, I can not avoid this.

**Comment by aleberti** [comment]
@giorgio-pirola I see you closed the issue, what was the solution?
